// Disclosure copy from plans/realtime-market-intelligence.md, section 10.2.
// SEBI_RISK_WARNING is SEBI's standard warning and must stay word for word,
// including its grammar. Never add a SEBI logo or "registered"/"approved" wording.
export const SEBI_RISK_WARNING =
  "Investment in securities market are subject to market risks. Read all the related documents carefully before investing.";

export default function Disclosure({ className = "" }: { className?: string }) {
  return (
    <p className={`max-w-[80ch] text-[12px] leading-5 text-muted ${className}`}>
      Samruddhi AI is a portfolio analytics and information service. It is not registered with SEBI as an Investment
      Adviser or Research Analyst, and it does not provide investment advice, research recommendations, buy/sell/hold
      calls, price targets or model portfolios. Market prices are delayed, not real-time. Analyses are generated by AI
      models (Amazon Nova Pro via AWS Bedrock) from the holdings you entered and public market information; they can be
      incomplete or wrong, and no human reviews them before you see them. {SEBI_RISK_WARNING} For advice suited to your
      situation, consult a SEBI-registered Investment Adviser (you can verify registration on{" "}
      <a
        href="https://www.sebi.gov.in"
        target="_blank"
        rel="noopener noreferrer"
        className="underline underline-offset-2 hover:text-ink"
      >
        sebi.gov.in
      </a>
      ).
    </p>
  );
}
